### ISSUE TITLE
Package not available for R version 3.1.0

### ISSUE THREAD

**Issue by brianspiering** [jknowles/EWStools#12]
Won't install after upgrade to R version 3.1.0

**Comment by cynthia0611** [comment]
I got error message when I try to install EWStools package, not sure how to fix it, could you give a hand?

> install.packages("EWStools")
> Warning in install.packages :
>   package ‘EWStools’ is not available (for R version 3.2.3)

**Comment by jknowles** [comment]
The package is not available on CRAN. The only way to use it is to use an installation out of GitHub:

```
devtools::install_github("jknowles/EWStools")
```

Right now there is not a plan to make EWStools available via CRAN.

**Comment by cynthia0611** [comment]
Thanks so much for quick reply! Got it installed! Also do you have user handbook, or could you please give an example how to use this package to build models?

**Comment by jknowles** [comment]
This article details the system EWStools was built to enable and includes an example script at the end which should be a good jumping off point: http://www.educationaldatamining.org/JEDM/index.php/JEDM/article/view/JEDM082

**Comment by cynthia0611** [comment]
Thanks for your guide and sharing!
